default_install_hook_types: ["pre-push"]
default_stages: ["push"]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
   - id: system
     name: Black
     entry: poetry run black .
     pass_filenames: false
     language: system
     stages: ["push"]
   - id: system
     name: isort
     entry: poetry run isort .
     pass_filenames: false
     language: system
     stages: ["push"]
   - id: system
     name: MyPy
     entry: poetry run mypy sugarjazy tests
     pass_filenames: false
     language: system
     stages: ["push"]
   - id: system
     name: Pylint
     entry: poetry run pylint -j 0 sugarjazy tests
     pass_filenames: false
     language: system
     stages: ["push"]
   - id: system
     name: Pylint
     entry: poetry run pytest
     pass_filenames: false
     language: system
     stages: ["push"]
