name: Python quality

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install poetry pylint
      run: |
        pip3 install --upgrade poetry
        poetry install -v
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --show-diff-on-failure --color=always --all-files --hook-stage=push
    - name: Generate code coverage
      run: |
        poetry run pytest --cov ./ --cov-report=xml --cov-fail-under 75
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true
